all:
  children:
    edge_vpn:
      hosts:
        pvvl-nbm01:

    edge_idp:
      hosts:
        pvvl-idp01:

    app_servers:
      hosts:
        pvvl-gnr01:
        pvvl-gnr02:

    monitoring:
      hosts:
        lvvl-utk01:

    backup:
      hosts:
        lvvl-tmp01:
