netbird_stack_version: "latest"
netbird_stack_dashboard_version: "latest"
netbird_stack_postgres_version: "17-alpine"
netbird_stack_deploy_dir: "/opt/whisper/netbird"
netbird_stack_docker_user: "dockeruser"
netbird_stack_log_level: "info"
netbird_stack_stun_port: 3478
netbird_stack_metrics_port: 9090
netbird_stack_healthcheck_port: 9000
netbird_stack_local_auth_disabled: false
netbird_stack_postgres_db: "netbird"
netbird_stack_postgres_user: "netbird"
netbird_stack_server_service_name: "netbird-server"
netbird_stack_dashboard_service_name: "dashboard"
netbird_stack_dashboard_auth_client_id: "netbird-dashboard"
netbird_stack_dashboard_auth_audience: "netbird-dashboard"
netbird_stack_dashboard_auth_supported_scopes: "openid profile email groups"
# netbird_stack_domain must be defined in the inventory
